# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(547, 493)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../PyConverter version 1.0/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.icon = QtWidgets.QLabel(self.centralwidget)
        self.icon.setGeometry(QtCore.QRect(170, 20, 191, 181))
        self.icon.setObjectName("icon")
        self.txt_oath = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_oath.setGeometry(QtCore.QRect(131, 201, 311, 20))
        self.txt_oath.setObjectName("txt_oath")
        self.converter = QtWidgets.QPushButton(self.centralwidget)
        self.converter.setGeometry(QtCore.QRect(89, 418, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.converter.setFont(font)
        self.converter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.converter.setStyleSheet("QPushButton{\n"
"border-radius: 15px;\n"
"color:rgb(222, 57, 95);;\n"
"background-color: rgb(234,234,234)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#fff;\n"
"background-color: rgb(222, 57, 95);\n"
"}")
        self.converter.setObjectName("converter")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 278, 49, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tiff = QtWidgets.QRadioButton(self.layoutWidget)
        self.tiff.setObjectName("tiff")
        self.verticalLayout.addWidget(self.tiff)
        self.png = QtWidgets.QRadioButton(self.layoutWidget)
        self.png.setObjectName("png")
        self.verticalLayout.addWidget(self.png)
        self.jpeg = QtWidgets.QRadioButton(self.layoutWidget)
        self.jpeg.setObjectName("jpeg")
        self.verticalLayout.addWidget(self.jpeg)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 200, 121, 20))
        self.label.setStyleSheet("QLabel:{\n"
"background-color:rgb(222, 57, 95);\n"
"}")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 200, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"color:rgb(222, 57, 95);;\n"
"background-color: rgb(234,234,234)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#fff;\n"
"background-color: rgb(222, 57, 95);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)


        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyConverter"))
        self.icon.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/converter/icon.png\"/></p><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">PYCONVERTER</span></p></body></html>"))
        self.converter.setText(_translate("MainWindow", "Converter"))
        self.tiff.setText(_translate("MainWindow", "TIFF"))
        self.png.setText(_translate("MainWindow", "PNG"))
        self.jpeg.setText(_translate("MainWindow", "JPEG"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Arquivo</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Abrir"))
import converter


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
